getting this error due to typescript packge 4.7 and above conflict with jest packages. for now ping the version to 4.6.3. We will have to revist this.
ERROR in ./src/extension/index.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/Users/weijie/code/neo/neo3-visual-tracker/node_modules/typescript/lib/typescript.js:42530:18)
    at /Users/weijie/code/neo/neo3-visual-tracker/node_modules/ts-loader/dist/servicesHost.js:679:18
    at /Users/weijie/code/neo/neo3-visual-tracker/node_modules/ts-loader/dist/servicesHost.js:118:141
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/weijie/code/neo/neo3-visual-tracker/node_modules/ts-loader/dist/servicesHost.js:118:124)
    at actualResolveTypeReferenceDirectiveNamesWorker (/Users/weijie/code/neo/neo3-visual-tracker/node_modules/typescript/lib/typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (/Users/weijie/code/neo/neo3-visual-tracker/node_modules/typescript/lib/typescript.js:116911:26)
    at processTypeReferenceDirectives (/Users/weijie/code/neo/neo3-visual-tracker/node_modules/typescript/lib/typescript.js:118393:31)
    at findSourceFileWorker (/Users/weijie/code/neo/neo3-visual-tracker/node_modules/typescript/lib/typescript.js:118278:21)
    at findSourceFile (/Users/weijie/code/neo/neo3-visual-tracker/node_modules/typescript/lib/typescript.js:118133:26)

webpack 5.37.0 compiled with 1 error in 1100 ms